default:
  http_metas:
    content-type: text/html

  metas:
    title:        kokada's portfolio
    description:  ポートフォリオ
    keywords:
    language:     ja
    robots:       index, follow

  stylesheets:    [reset.css, text.css, 960.css, main.css, style.css]

  javascripts:    [jquery.min.js, jquery.timelinr-0.9.6.js]

  has_layout:     true
  layout:         layout
